name: CI/CD Pipeline

# Define the events 
on:
  push:
    branches:
      - main  # Trigger pipeline on push to main branch
  pull_request:
    branches:
      - main  # Trigger pipeline on pull requests to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Specify the operating system to use for the runner

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2  # Use the actions/checkout action to fetch the repository code

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2  # Use the actions/setup-node action to set up Node.js
        with:
          node-version: '16'  # Specify the Node.js version to use

      # Step 3: Install Docker
      - name: Install Docker
        run: |
          curl -fsSL https://get.docker.com -o get-docker.sh  # Download Docker installation script
          sh get-docker.sh  # Run Docker installation script

      # Step 4: Install frontend dependencies
      - name: Install frontend dependencies
        run: |
          npm install  

      # Step 5: Install backend dependencies
      - name: Install backend dependencies
        run: |
          cd backend 
          npm install  

      # Step 6: Build Docker image for the frontend
      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sportnewsapp-frontend:latest -f Dockerfile.frontend .  

      # Step 7: Build Docker image for the backend
      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sportnewsapp-backend:latest -f backend/Dockerfile .  

      # Step 8: Authenticate with Docker Hub
      - name: Docker login
        uses: docker/login-action@v2  # Use the docker/login-action to authenticate with Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Use Docker username from secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Use Docker password from secrets

      # Step 9: Push frontend Docker image to Docker Hub
      - name: Push frontend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sportnewsapp-frontend:latest  

      # Step 10: Push backend Docker image to Docker Hub
      - name: Push backend Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sportnewsapp-backend:latest  

     
    